#!/usr/bin/env python3
"""Generate 8 original public wavetables. Not product ROM. MIT."""
from __future__ import annotations

import math
from pathlib import Path

N = 256
PEAK = 29200  # ~0.89 * 32767


def norm(samples: list[float]) -> list[int]:
    m = max(abs(x) for x in samples) or 1.0
    return [max(-32767, min(32767, int(round(x / m * PEAK)))) for x in samples]


def sine(i: int) -> float:
    return math.sin(2 * math.pi * i / N)


def triangle(i: int) -> float:
    x = i / N
    if x < 0.25:
        return x * 4
    if x < 0.75:
        return 2 - x * 4
    return x * 4 - 4


def saw(i: int) -> float:
    return 2 * (i / N) - 1


def square(i: int) -> float:
    return 1.0 if i < N // 2 else -1.0


def pulse(i: int) -> float:
    return 1.0 if i < N // 4 else -1.0


def organ(i: int) -> float:
    t = 2 * math.pi * i / N
    return math.sin(t) + 0.5 * math.sin(3 * t) + 0.25 * math.sin(5 * t)


def bell(i: int) -> float:
    t = 2 * math.pi * i / N
    return math.sin(t) + 0.35 * math.sin(2.76 * t) + 0.18 * math.sin(5.41 * t)


def noise(i: int) -> float:
    x = 0xC0FFEE ^ (i * 1103515245 + 12345)
    x = (x >> 8) & 0xFFFF
    return (x / 32767.5) - 1.0


WAVES = [
    ("Sine", sine),
    ("Triangle", triangle),
    ("Saw", saw),
    ("Square", square),
    ("Pulse", pulse),
    ("Organ", organ),
    ("Bell", bell),
    ("Noise", noise),
]


def c_rows(vals: list[int]) -> str:
    lines = []
    for r in range(0, N, 16):
        chunk = ", ".join(f"{v:6d}" for v in vals[r : r + 16])
        lines.append("    " + chunk + ",")
    return "\n".join(lines)


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    tables = [norm([fn(i) for i in range(N)]) for _, fn in WAVES]

    c_body = []
    c_body.append("/* Generated by scripts/gen_wavetable8.py — original MIT tables, not product ROM. */")
    c_body.append("#include \"AudioSynthWavetable8.h\"")
    c_body.append("")
    c_body.append("const int16_t audio_wt8[AUDIO_WT8_COUNT][AUDIO_WT8_LEN] = {")
    for idx, ((name, _), vals) in enumerate(zip(WAVES, tables)):
        c_body.append(f"  /* {idx} {name} */")
        c_body.append("  {")
        c_body.append(c_rows(vals))
        c_body.append("  },")
    c_body.append("};")
    c_body.append("")
    (root / "src" / "AudioSynthWavetable8_tables.cpp").write_text("\n".join(c_body) + "\n", encoding="utf-8")

    js = [
        "/* Generated by scripts/gen_wavetable8.py — original MIT tables, not product ROM. */",
        "window.WT8_LEN = 256;",
        "window.WT8_NAMES = [",
    ]
    js += [f'  "{n}",' for n, _ in WAVES]
    js.append("];")
    js.append("window.WT8 = [")
    for vals in tables:
        js.append("  new Int16Array([")
        for r in range(0, N, 16):
            js.append("    " + ", ".join(str(v) for v in vals[r : r + 16]) + ",")
        js.append("  ]),")
    js.append("];")
    (root / "examples" / "octopus-pwa" / "wt8.js").write_text("\n".join(js) + "\n", encoding="utf-8")
    print("wrote tables")


if __name__ == "__main__":
    main()
